# Generated by Django 4.2.3 on 2023-07-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=32, null=True)),
                ("second_name", models.CharField(blank=True, max_length=32, null=True)),
                ("dob", models.DateField()),
            ],
        ),
    ]
