# Generated by Django 4.2.3 on 2023-07-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_userinfo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="upload",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
